#!/usr/bin/env bash
# Script for transferring a file from a client to a server.
# Accepts four parameters:
# - The path to the file to be transferred.
# - The IP address of the server.
# - The username for the scp connection.
# - The path to the SSH private key used by scp.
# Displays usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY
# if fewer than four parameters are passed.
# scp command transfers the file to the user's home directory ~/
# Strict host key checking must be disabled when using scp.

if [ $# -lt 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi
