#!/usr/bin/env bash
# Bash script that displays a list of currently running processes
#+ Show all processes, for all users, including those
#+ which might not have a TTY
#+ Show process hierarchy

ps -a uf
